name: piece_inr
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.6.0
  - blas=1.0
  - blosc=1.21.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - cfitsio=3.470
  - charls=2.2.0
  - contourpy=1.2.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - expat=2.6.4
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.12.1
  - giflib=5.2.2
  - icu=73.1
  - imagecodecs=2024.9.22
  - imageio=2.37.0
  - importlib_resources=6.4.0
  - intel-openmp=2023.1.0
  - jpeg=9e
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy_loader=0.4
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libavif=1.1.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcups=2.4.2
  - libcurl=8.12.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=4.25.3
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - libzopfli=1.0.3
  - lz4-c=1.9.4
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mysql=8.4.0
  - ncurses=6.4
  - networkx=3.2.1
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.0.16
  - packaging=24.2
  - pcre2=10.42
  - pip=25.0
  - pybind11-abi=4
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - python=3.9.21
  - python-dateutil=2.9.0post0
  - qtbase=6.7.2
  - qtdeclarative=6.7.2
  - qtsvg=6.7.2
  - qttools=6.7.2
  - qtwebchannel=6.7.2
  - qtwebsockets=6.7.2
  - readline=8.2
  - scikit-image=0.24.0
  - scipy=1.13.1
  - setuptools=75.8.0
  - sip=6.10.0
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tifffile=2023.4.12
  - tk=8.6.14
  - tomli=2.0.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - tzdata=2025a
  - unicodedata2=15.1.0
  - wheel=0.45.1
  - xcb-util-cursor=0.1.4
  - xz=5.6.4
  - zfp=1.0.0
  - zipp=3.21.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.6
  - pip:
      - asttokens==3.0.0
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - comm==0.2.2
      - debugpy==1.8.13
      - decorator==5.2.1
      - einops==0.8.1
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - filelock==3.13.1
      - fsspec==2024.6.1
      - idna==3.4
      - importlib-metadata==8.6.1
      - ipykernel==6.29.5
      - ipython==8.18.1
      - jedi==0.19.2
      - jinja2==3.1.4
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - lpips==0.1.4
      - markupsafe==2.1.5
      - matplotlib-inline==0.1.7
      - microscpsf-py==0.2
      - mpmath==1.3.0
      - nest-asyncio==1.6.0
      - numpy==1.26.3
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - nvitop==1.4.2
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.3.7
      - prompt-toolkit==3.0.50
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.1
      - pyyaml==6.0.2
      - pyzmq==26.3.0
      - requests==2.28.1
      - stack-data==0.6.3
      - sympy==1.13.1
      - torch==2.6.0
      - torchvision==0.21.0
      - traitlets==5.14.3
      - triton==3.2.0
      - typing-extensions==4.12.2
      - urllib3==1.26.13
      - wcwidth==0.2.13

